# Logistic Regression

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [40]:
x= np.arange(10).reshape(-1,1)
y=np.array([0,0,0,0,1,1,1,1,1,1])

In [41]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [42]:
y

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [43]:
model = LogisticRegression( solver = 'liblinear', random_state = 0 )

In [44]:
model.fit(x,y)

LogisticRegression(random_state=0, solver='liblinear')

In [45]:
model.classes_

array([0, 1])

In [46]:
model.intercept_

array([-1.04608067])

In [47]:
model.coef_

array([[0.51491375]])

In [48]:
model.predict_proba(x)

array([[0.74002157, 0.25997843],
       [0.62975524, 0.37024476],
       [0.5040632 , 0.4959368 ],
       [0.37785549, 0.62214451],
       [0.26628093, 0.73371907],
       [0.17821501, 0.82178499],
       [0.11472079, 0.88527921],
       [0.07186982, 0.92813018],
       [0.04422513, 0.95577487],
       [0.02690569, 0.97309431]])

In [49]:
model.predict(x)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import StandardScaler

In [51]:
path_in = "https://raw.githubusercontent.com/abdoghareeb46/Predict-Customer-Churn/master/ChurnData.csv"

In [52]:
df = pd.read_csv(path_in)

In [53]:
df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,...,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,...,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0.0

In [54]:
df.shape

(200, 28)

In [55]:
type(df)

pandas.core.frame.DataFrame

In [56]:
df.describe()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
count,200.000000,200.000000,200.000000,200.000000,200.00000,200.00000,200.000000,200.000000,200.000000,200.00000,...,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,35.505000,41.165000,11.650000,75.130000,2.82500,10.22500,0.425000,0.705000,0.290000,11.78925,...,0.275000,0.440000,0.45500,0.460000,0.440000,2.193285,3.229185,3.951015,2.475000,0.290000
std,21.640971,13.076803,10.158419,128.430468,1.28555,8.95743,0.495584,0.457187,0.454901,9.88725,...,0.447635,0.497633,0.49922,0.499648,0.497633,0.731282,0.281019,0.752553,1.079445,0.454901
min,1.000000,19.000000,0.000000,9.000000,1.00000,0.00000,0.000000,0.000000,0.000000,1.10000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.095000,1.749000,2.197000,1.000000,0.000000
25%,16.750000,31.000000,3.000000,31.000000,2.00000,3.00000,0.000000,0.000000,0.000000,5.53750,...,0.000000,0.000000,0.00000,0.000000,0.000000,1.711750,3.226500,3.434000,2.000000,0.000000
50%,33.500000,40.000000,9.000000,48.000000,3.00000,7.50000,0.000000,1.000000,0.000000,8.25000,...,0.000000,0.000000,0.00000,0.000000,0.000000,2.110000,3.240000,3.871000,2.000000,0.000000
75%,55.250000,51.000000,18.000000,80.000000,4.00000,17.00000,1.000000,1.000000,1.000000,14.30000,...,1.000000,1.000000,1.00000,1.000000,1.000000,2.660000,3.240000,4.382000,3.000000,1.000000
max,72.000000,76.000000,48.000000,1668.000000,5.00000,44.00000,1.000000,1.000000,1.000000,62.30000,...,1.000000,1.000000,1.00000,1.000000,1.000000,4.132000,4.227000,7.419000,4.000000,1.000000

In [57]:
df = df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
#churn_df['churn'] =df['churn'].astype('int')
df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0.0

In [58]:
df.shape

(200, 10)

In [59]:
X = df.drop('churn', 1)
y = df.churn

In [60]:
lg = LogisticRegression(C=0.01, solver='liblinear')

In [61]:
lg.fit(X, y)

LogisticRegression(C=0.01, solver='liblinear')

In [62]:
yhat = lg.predict(X)

In [63]:
yhat

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
yhat_prob = lg.predict_proba(X)
yhat_prob

array([[0.44650058, 0.55349942],
       [0.65361551, 0.34638449],
       [0.64441736, 0.35558264],
       [0.78524189, 0.21475811],
       [0.72228948, 0.27771052],
       [0.9714447 , 0.0285553 ],
       [0.78232044, 0.21767956],
       [0.49385656, 0.50614344],
       [0.90816138, 0.09183862],
       [0.91030133, 0.08969867],
       [0.91135115, 0.08864885],
       [0.82957944, 0.17042056],
       [0.9407983 , 0.0592017 ],
       [0.94352214, 0.05647786],
       [0.56698311, 0.43301689],
       [0.40691698, 0.59308302],
       [0.61307659, 0.38692341],
       [0.60966207, 0.39033793],
       [0.8151572 , 0.1848428 ],
       [0.52643664, 0.47356336],
       [0.81496021, 0.18503979],
       [0.39847776, 0.60152224],
       [0.63929496, 0.36070504],
       [0.5151577 , 0.4848423 ],
       [0.70091282, 0.29908718],
       [0.46009372, 0.53990628],
       [0.945296  , 0.054704  ],
       [0.83629836, 0.16370164],
       [0.47499694, 0.52500306],
       [0.49712308, 0.50287692],
       [0.76497255, 0.23502745],
       [0.9755107 , 0.0244893 ],
       [0.49511309, 0.50488691],
       [0.6186203 , 0.3813797 ],
       [0.56096841, 0.43903159],
       [0.96060827, 0.03939173],
       [0.74548711, 0.25451289],
       [0.64869113, 0.35130887],
       [0.76512015, 0.23487985],
       [0.83953916, 0.16046084],
       [0.49876856, 0.50123144],
       [0.87548701, 0.12451299],
       [0.87483961, 0.12516039],
       [0.78644361, 0.21355639],
       [0.68183974, 0.31816026],
       [0.89583092, 0.10416908],
       [0.85812758, 0.14187242],
       [0.79573839, 0.20426161],
       [0.98355288, 0.01644712],
       [0.91655083, 0.08344917],
       [0.92672703, 0.07327297],
       [0.68255245, 0.31744755],
       [0.74934962, 0.25065038],
       [0.86476709, 0.13523291],
       [0.34601518, 0.65398482],
       [0.57886773, 0.42113227],
       [0.54646814, 0.45353186],
       [0.45015529, 0.54984471],
       [0.55129807, 0.44870193],
       [0.45283965, 0.54716035],
       [0.96655491, 0.03344509],
       [0.87296094, 0.12703906],
       [0.96170413, 0.03829587],
       [0.56873307, 0.43126693],
       [0.58381812, 0.41618188],
       [0.82180743, 0.17819257],
       [0.88658709, 0.11341291],
       [0.92400952, 0.07599048],
       [0.60702207, 0.39297793],
       [0.97102045, 0.02897955],
       [0.77789665, 0.22210335],
       [0.82384809, 0.17615191],
       [0.67544488, 0.32455512],
       [0.84544878, 0.15455122],
       [0.72656356, 0.27343644],
       [0.87756967, 0.12243033],
       [0.87739199, 0.12260801],
       [0.35831899, 0.64168101],
       [0.95798443, 0.04201557],
       [0.65006435, 0.34993565],
       [0.8946947 , 0.1053053 ],
       [0.83927962, 0.16072038],
       [0.68879347, 0.31120653],
       [0.58037402, 0.41962598],
       [0.55768832, 0.44231168],
       [0.6726019 , 0.3273981 ],
       [0.59814556, 0.40185444],
       [0.95843815, 0.04156185],
       [0.38830065, 0.61169935],
       [0.47478401, 0.52521599],
       [0.53831496, 0.46168504],
       [0.38453233, 0.61546767],
       [0.72782218, 0.27217782],
       [0.55987785, 0.44012215],
       [0.97017983, 0.02982017],
       [0.42433702, 0.57566298],
       [0.9405449 , 0.0594551 ],
       [0.91565127, 0.08434873],
       [0.92561312, 0.07438688],
       [0.83974257, 0.16025743],
       [0.35741835, 0.64258165],
       [0.5872296 , 0.4127704 ],
       [0.58554953, 0.41445047],
       [0.93473011, 0.06526989],
       [0.40891671, 0.59108329],
       [0.59936986, 0.40063014],
       [0.5028477 , 0.4971523 ],
       [0.43790141, 0.56209859],
       [0.79096015, 0.20903985],
       [0.74636863, 0.25363137],
       [0.83325765, 0.16674235],
       [0.5549985 , 0.4450015 ],
       [0.85569063, 0.14430937],
       [0.52273894, 0.47726106],
       [0.38732555, 0.61267445],
       [0.41074867, 0.58925133],
       [0.96754795, 0.03245205],
       [0.46281467, 0.53718533],
       [0.57616347, 0.42383653],
       [0.71889287, 0.28110713],
       [0.45036702, 0.54963298],
       [0.40423539, 0.59576461],
       [0.55779371, 0.44220629],
       [0.46776461, 0.53223539],
       [0.94864768, 0.05135232],
       [0.92556883, 0.07443117],
       [0.91195612, 0.08804388],
       [0.52076605, 0.47923395],
       [0.75812088, 0.24187912],
       [0.6659187 , 0.3340813 ],
       [0.99462366, 0.00537634],
       [0.56818227, 0.43181773],
       [0.84414388, 0.15585612],
       [0.90965495, 0.09034505],
       [0.69293908, 0.30706092],
       [0.97386512, 0.02613488],
       [0.54716265, 0.45283735],
       [0.66052371, 0.33947629],
       [0.65804082, 0.34195918],
       [0.50458171, 0.49541829],
       [0.6378384 , 0.3621616 ],
       [0.88469148, 0.11530852],
       [0.95248345, 0.04751655],
       [0.84432306, 0.15567694],
       [0.71434221, 0.28565779],
       [0.90228356, 0.09771644],
       [0.52073182, 0.47926818],
       [0.91119114, 0.08880886],
       [0.47983487, 0.52016513],
       [0.56093621, 0.43906379],
       [0.70418322, 0.29581678],
       [0.54832657, 0.45167343],
       [0.609675  , 0.390325  ],
       [0.81789132, 0.18210868],
       [0.98608112, 0.01391888],
       [0.8151988 , 0.1848012 ],
       [0.48715955, 0.51284045],
       [0.4995869 , 0.5004131 ],
       [0.83974697, 0.16025303],
       [0.4674142 , 0.5325858 ],
       [0.54900934, 0.45099066],
       [0.86391977, 0.13608023],
       [0.85943579, 0.14056421],
       [0.81285448, 0.18714552],
       [0.93685441, 0.06314559],
       [0.74993244, 0.25006756],
       [0.95024231, 0.04975769],
       [0.40009427, 0.59990573],
       [0.83924714, 0.16075286],
       [0.78486357, 0.21513643],
       [0.57393963, 0.42606037],
       [0.74164331, 0.25835669],
       [0.49784527, 0.50215473],
       [0.56715907, 0.43284093],
       [0.57578834, 0.42421166],
       [0.9052282 , 0.0947718 ],
       [0.81906445, 0.18093555],
       [0.87291629, 0.12708371],
       [0.72939689, 0.27060311],
       [0.92536638, 0.07463362],
       [0.8666475 , 0.1333525 ],
       [0.96896348, 0.03103652],
       [0.9016172 , 0.0983828 ],
       [0.93356189, 0.06643811],
       [0.91041253, 0.08958747],
       [0.73456735, 0.26543265],
       [0.47222137, 0.52777863],
       [0.87672922, 0.12327078],
       [0.86591752, 0.13408248],
       [0.93329245, 0.06670755],
       [0.95569464, 0.04430536],
       [0.44433057, 0.55566943],
       [0.64442665, 0.35557335],
       [0.95023435, 0.04976565],
       [0.96349054, 0.03650946],
       [0.96161284, 0.03838716],
       [0.78601908, 0.21398092],
       [0.66488444, 0.33511556],
       [0.5694    , 0.4306    ],
       [0.94681556, 0.05318444]])

In [66]:
confusion_matrix(y, yhat)

array([[127,  15],
       [ 39,  19]])